import {
  Building2,
  Calculator,
  BarChart3,
  Headphones,
  Bot,
  Sparkles,
  Cpu,
  ClipboardList,
  SearchCode,
  Database,
  FileSignature,
  KanbanSquare,
  ListTodo,
  GitMerge,
  PieChart,
  Users,
  BarChart2,
  Activity,
  Map,
  Truck,
  Percent,
  Megaphone,
  Briefcase,
  Store,
  FileText,
  Palmtree,
  Clock,
  LayoutDashboard,
  ShieldAlert,
  CalendarDays,
  Coins,
  FileSearch,
  BadgeAlert,
  FileCheck,
  Fingerprint,
  HandCoins,
  Mail,
  UserMinus,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const ICON_MAP: Record<string, LucideIcon> = {
  // Base
  'building-2': Building2,
  'calculator': Calculator,
  'bar-chart-3': BarChart3,
  'headphones': Headphones,
  'bot': Bot,
  'sparkles': Sparkles,
  'cpu': Cpu,
  'clipboard-list': ClipboardList,
  
  // Expanded for specific systems
  'search-code': SearchCode,
  'database': Database,
  'file-signature': FileSignature,
  'kanban': KanbanSquare,
  'list-todo': ListTodo,
  'git-merge': GitMerge,
  'pie-chart': PieChart,
  'users': Users,
  'bar-chart-2': BarChart2,
  'activity': Activity,
  'map': Map,
  'truck': Truck,
  'percent': Percent,
  'megaphone': Megaphone,
  'briefcase': Briefcase,
  'store': Store,
  'file-text': FileText,
  'palmtree': Palmtree,
  'clock': Clock,
  'layout-dashboard': LayoutDashboard,
  'shield-alert': ShieldAlert,
  'calendar-days': CalendarDays,
  'coins': Coins,
  'file-search': FileSearch,
  'badge-alert': BadgeAlert,
  'file-check': FileCheck,
  'fingerprint': Fingerprint,
  'hand-coins': HandCoins,
  'mail': Mail,
  'user-minus': UserMinus,
}
